"""
Django settings for meicoauth project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from meicobaseapi.config import load_secrets
import environ

secrets = load_secrets()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False),
)
environ.Env.read_env()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = secrets.get("SECRETKEY")
SECRET_KEY_2 = secrets.get("SECRET_KEY_2")

# Configuracion JWT Azure
TENANT_ID = secrets.get("TENANT_ID")
CLIENT_ID = secrets.get("CLIENT_ID")
JWKS_URI = secrets.get("JWKSURI")
ISSUER = secrets.get("ISSUER")

# Configuracion PyJWT
SECRET = secrets.get("SECRET")
ACCESS_TOKEN_EXPIRATION = "1"
REFRESH_TOKEN_EXPIRATION = "5"
ALGORITHM_TOKEN = "HS256"


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

GOANYWHERE_PAYLOAD_APLICACIONES_URL = "https://mftprb.meico.com.co/rest/forms/v1/obtenermenuportaldeaplicaciones/payload"
GOANYWHERE_USER = secrets.get("GOANYWHEREUSER")
GOANYWHERE_PASSWORD = secrets.get("GOANYWHEREPASSWORD")


# Application definition

INSTALLED_APPS = [
    "django.contrib.staticfiles",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "meicobaseapi",
    "rest_framework",
    "drf_yasg",
    'corsheaders',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

ROOT_URLCONF = "meicobaseapi.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "meicobaseapi.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
print("Configurando la base de datos con los siguientes parámetros:")

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': env("DBNAME"),
        'USER': env("DBUSER"),
        'PASSWORD': env("DBPASSWORD"),
        'HOST': env("DBHOST"),
        #'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server'
            #'driver': 'pymssql',
            #'Trusted_Connection': 'yes',
        },
    }
}

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}

#MIGRATION_MODULES = {"auth": None, "contenttypes": None}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "meicobaseapi.core.authentication.TokenValidate",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "meicobaseapi.core.authentication.AllowAnonymous",
    ],
    "EXCEPTION_HANDLER": "meicobaseapi.core.exception_handler.custom_exception_handler",
}

SWAGGER_SETTINGS = {
    "SECURITY_DEFINITIONS": {
        "Bearer": {"type": "apiKey", "name": "Authorization", "in": "header"},
    }
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "https://portal.meico.local",
    "http://localhost:4201",
    "http://localhost:4202",
    "http://localhost:4300",
]

CORS_ALLOW_HEADERS = [
    "content-type",
    "authorization",
    "x-requested-with",
    "accept",
    "origin",
    "x-csrftoken",
    "zonahoraria",
    'idempresa',
    'idaplicacion',
    'transactionid',
]
